version: "3"
services:
  db:
    image: "postgres"
    container_name: "django_rest_db"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123Admin456
      - POSTGRES_DB=django_rest
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data